In [3]:
!pip install tensorflow

     |████████████████████████████████| 175.5 MB 8.1 MB/s 
     |████████████████████████████████| 65 kB 7.8 MB/s 
     |████████████████████████████████| 1.0 MB 11.4 MB/s 
     |████████████████████████████████| 10.6 MB 12.5 MB/s 
     |████████████████████████████████| 42 kB 3.4 MB/s 
     |████████████████████████████████| 127 kB 11.9 MB/s 
     |████████████████████████████████| 462 kB 11.9 MB/s 
     |████████████████████████████████| 3.3 MB 4.0 MB/s 
     |████████████████████████████████| 57 kB 9.4 MB/s 
     |████████████████████████████████| 96 kB 8.7 MB/s 
     |████████████████████████████████| 114 kB 11.5 MB/s 
     |████████████████████████████████| 779 kB 12.4 MB/s 
     |████████████████████████████████| 155 kB 11.6 MB/s 
     |████████████████████████████████| 147 kB 11.3 MB/s 
     |████████████████████████████████| 77 kB 9.4 MB/s 
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=1095f9cf3cabc0d7b32981e6f31f73b6f761904aaeb51a25c

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.4.0'

In [8]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [34]:
print(dataset.values[0, :])

[1 15634602 'Hargrave' 619 'France' 'Female' 42 2 0.0 1 1 1 101348.88 1]


In [29]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


In [12]:
# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [24]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [25]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

In [26]:
ann.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

In [27]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [28]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 1s 725us/step - loss: 0.8699 - accuracy: 0.4008
Epoch 2/100
250/250 [==============================] - 0s 659us/step - loss: 0.4902 - accuracy: 0.7991
Epoch 3/100
250/250 [==============================] - 0s 630us/step - loss: 0.4467 - accuracy: 0.7987
Epoch 4/100
250/250 [==============================] - 0s 647us/step - loss: 0.4255 - accuracy: 0.8117
Epoch 5/100
250/250 [==============================] - 0s 628us/step - loss: 0.4127 - accuracy: 0.8144
Epoch 6/100
250/250 [==============================] - 0s 641us/step - loss: 0.3972 - accuracy: 0.8253
Epoch 7/100
250/250 [==============================] - 0s 598us/step - loss: 0.3969 - accuracy: 0.8302
Epoch 8/100
250/250 [==============================] - 0s 590us/step - loss: 0.3849 - accuracy: 0.8320
Epoch 9/100
250/250 [==============================] - 0s 689us/step - loss: 0.3641 - accuracy: 0.8435
Epoch 10/100
250/250 [==============================] - 0s 594us/step - l

In [49]:
# new_X = [[1.0 ,0.0 ,0.0, 600, 0, 40, ]]
new_X = [[1.0, 0.0, 0.0, 600, 1.0, 40, 3, 60000.00, 2, 1, 1, 50000.00]]

In [50]:
print(new_X)

[[1.0, 0.0, 0.0, 600, 1.0, 40, 3, 60000.0, 2, 1, 1, 50000.0]]


In [51]:
print(sc.transform(new_X))

[[ 1.00150113 -0.58312392 -0.57273139 -0.52046273  0.91509065  0.10629772
  -0.70174202 -0.26396987  0.80225696  0.64376017  0.97725852 -0.87097985]]


In [52]:
new_X = sc.transform(new_X)

In [53]:
y_pred = ann.predict(new_X)

In [55]:
print(y_pred > 0.5)

[[False]]


In [57]:
y_pred = ann.predict(X_test ) > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1540   45]
 [ 233  182]]


0.861